// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_events.h"
extern lv_obj_t *ui_Screen1;
void ui_event_Arc2( lv_event_t * e);
extern lv_obj_t *ui_Arc2;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui____initial_actions0;




LV_FONT_DECLARE( ui_font_fotn2);
LV_FONT_DECLARE( ui_font_fotn3);
LV_FONT_DECLARE( ui_font_fotn4);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
